### ISSUE TITLE
Automatically Load Previews

### ISSUE THREAD

**Issue by jonlguk** [joakin/context-cards#7]
Hi is it possible to automatically load the Wikipedia preview when the page loads?

**Comment by joakin** [comment]
Can you expand on what you mean?

On October 26, 2020, Moandji Ezana <notifications@github.com> wrote:
> Hi is it possible to automatically load the Wikipedia preview when the

> page loads?
>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/joakin/context-cards/issues/7>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAFATL2KLBH4NKZQSHMVHGDSMWJ2RANCNFSM4S7RQ3LA>.

**Comment by jonlguk** [comment]
Hi thanks for getting back to me.  I want to automatically load previews so they are embedded in webpages, without having to hover on a word.

**Comment by jonlguk** [comment]
Sorry to pester you, please can you let me know.

**Comment by joakin** [comment]
Well if you need a quick answer, the answer is no, sorry. This is a library for page previews on hover, not a 3rd party library to render Wikimedia summaries.
